export const ENV = {
  PORT: process.env.PORT || 4000,
  CLIENT_URL: process.env.CLIENT_URL!,
  DATABASE_URL: process.env.DATABASE_URL!,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME!,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET!,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY!,
  CLERK_PUBLISHABLE_KEY: process.env.CLERK_PUBLISHABLE_KEY!,
  CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY!,
  CLERK_WEBHOOK_KEY: process.env.CLERK_WEBHOOK_KEY!,
};
